[Settings]
ID = "predictament"

[build]
  environment = { GATSBY_ENV = "production" }

# Deploy Preview context: All Deploy Previews (https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/)
# will inherit these settings.
[context.deploy-preview]
  environment = { GATSBY_ENV = "test" }

# Test context: All deploys of the test branch will inherit these settings.
[context.branch-deploy]
  environment = { GATSBY_ENV = "test" }

[context."test"]
  environment = { GATSBY_ENV = "test" }
